integration test trial

diff --git a/.github/workflows/job-deploy.yml b/.github/workflows/job-deploy.yml
--- a/.github/workflows/job-deploy.yml
+++ b/.github/workflows/job-deploy.yml
@@ -42,19 +42,7 @@ jobs:
         run: docker ps -a
 
       - name: wait for MySQL
-        run: sleep 30
-
-      - name: Wait for MySQL to be ready
-        env:
-          DB_HOST: ${{ secrets.DB_HOST }}
-          DB_PORT: ${{ secrets.DB_PORT }}
-        run: |
-          for i in {1..30}; do
-            nc -z "$DB_HOST" "$DB_PORT" && echo "MySQL is up!" && exit 0
-            echo "Waiting for MySQL at $DB_HOST:$DB_PORT..."
-            sleep 2
-          done
-          echo "MySQL failed to start" && exit 1
+        run: sleep 60
 
       - name: Debug network issues
         run: |
@@ -63,8 +51,18 @@ jobs:
           cat /etc/hosts
           docker ps
           docker logs book-db
-          
 
+      - name: Wait for MySQL to be ready
+        env:
+          DB_HOST: ${{ secrets.DB_HOST }}
+          DB_PORT: ${{ secrets.DB_PORT }}
+        run: |
+          for i in {1..30}; do
+            nc -z "$DB_HOST" "$DB_PORT" && echo "ready for connections!" && exit 0
+            echo "Waiting for MySQL at $DB_HOST:$DB_PORT..."
+            sleep 2
+          done
+          echo "MySQL failed to start" && exit 1
 
       - name: Checkout repository
         uses: actions/checkout@v3
